# Site settings
title: Chi-Hieu Pham's blog
email: 
description: "Computer Scientist."
baseurl: ""
url: "http://chieupham.github.io"
github_username:  chieupham

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
